"""Parity test: the Python engine must reproduce the original TypeScript engine
exactly, for all 200 catalogue products, on every metric the interface shows.

The golden fixture is generated by bundling the original src/engine with
rolldown and running it under Node (see tests/README.md).
"""
from __future__ import annotations

import json
import math
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from app.data.catalog import build_catalog_products
from app.domain import DEFAULT_SETTINGS
from app.engine.insights import portfolio_insights
from app.engine.recommendations import recommendations_for
from app.engine.scenarios import run_scenarios
from app.engine.sensitivity import tornado
from app.engine.valuation import compute_priority, value_product

GOLDEN = os.environ.get(
    "GOLDEN", os.path.join(os.path.dirname(__file__), "golden.json"))
TOL = 1e-6


def j(v):
    if isinstance(v, str):
        return math.inf if v == "Infinity" else math.nan
    return v


def close(a, b, tol=TOL):
    a, b = j(a), j(b)
    if isinstance(a, float) and math.isnan(a):
        return isinstance(b, float) and math.isnan(b)
    if math.isinf(a) or math.isinf(b):
        return a == b
    return abs(a - b) <= max(tol, abs(b) * 1e-9)


def main() -> int:
    golden = json.loads(open(GOLDEN, encoding="utf-8").read())
    settings = DEFAULT_SETTINGS
    products = build_catalog_products(settings)
    vals = [(p, value_product(p, settings)) for p in products]
    max_value = max([1.0] + [v["threeYearValue"] for _, v in vals])
    rows = [{"product": p, "valuation": v,
             "priority": compute_priority(v, p, settings["priorityWeights"], max_value)}
            for p, v in vals]

    fails = []
    checks = 0

    def check(cond, label):
        nonlocal checks
        checks += 1
        if not cond:
            fails.append(label)

    assert len(rows) == len(golden["products"]), "product count differs"

    for row, g in zip(rows, golden["products"]):
        p, v, pr = row["product"], row["valuation"], row["priority"]
        tag = g["code"]
        check(p["id"] == g["id"], f"{tag} id")
        check(p["name"] == g["name"], f"{tag} name")
        check(p["lifecycle"] == g["lifecycle"], f"{tag} lifecycle")
        check(p["strategicPriority"] == g["priorityLabel"], f"{tag} strategicPriority")
        check(p["investment"]["buildMonths"] == g["buildMonths"], f"{tag} buildMonths")
        check(p["tags"] == g["tags"], f"{tag} tags")
        check(p["description"] == g["description"], f"{tag} description")
        check(p["problemStatement"] == g["problemStatement"], f"{tag} problemStatement")
        check(p["targetUsers"] == g["targetUsers"], f"{tag} targetUsers")
        check(p["usageFrequency"] == g["usageFrequency"], f"{tag} usageFrequency")
        check(p["geographicScope"] == g["geographicScope"], f"{tag} geographicScope")
        check(p["complexity"] == g["complexity"], f"{tag} complexity")
        check(p["timeToValueMonths"] == g["timeToValueMonths"], f"{tag} timeToValue")
        check(p["userCount"] == g["userCount"], f"{tag} userCount")
        check(p["strategic"] == g["strategic"], f"{tag} strategic")
        check(p["confidence"] == g["confidenceInputs"], f"{tag} confidenceInputs")

        # benefit construction
        check(len(p["benefits"]) == g["benefitCount"], f"{tag} benefitCount")
        for b, gb in zip(p["benefits"], g["benefits"]):
            check(b["kind"] == gb["kind"], f"{tag} benefit kind")
            check(b["label"] == gb["label"], f"{tag} benefit label")
            check(close(b["attribution"], gb["attribution"]), f"{tag} benefit attribution")
            check(b["rampMonths"] == gb["ramp"], f"{tag} benefit ramp")
            check(b["startMonth"] == gb["start"], f"{tag} benefit start")
            check(b["evidence"] == gb["evidence"], f"{tag} benefit evidence")
            check(b["evidenceStrength"] == gb["stars"], f"{tag} benefit stars")
            for k, gv in gb["inputs"].items():
                check(close(b["inputs"][k], gv), f"{tag} benefit input {k}")

        # headline financials
        for key, gk in [("annualGrossValue", "annualGrossValue"), ("netAnnualValue", "netAnnualValue"),
                        ("threeYearValue", "threeYearValue"), ("fiveYearValue", "fiveYearValue"),
                        ("horizonValue", "horizonValue"), ("totalBenefits", "totalBenefits"),
                        ("totalCosts", "totalCosts"), ("roi", "roi"), ("npv", "npv"), ("irr", "irr"),
                        ("hardDollarValue", "hardDollarValue"), ("softValue", "softValue"),
                        ("fteEquivalent", "fteEquivalent"),
                        ("capacityReleaseHours", "capacityReleaseHours"),
                        ("valuePerDollar", "valuePerDollar")]:
            check(close(v[key], g[gk]), f"{tag} {key} ({v[key]} vs {g[gk]})")
        check(close(v["paybackMonths"], g["payback"]), f"{tag} payback")
        check(close(v["paybackFromGoLive"], g["paybackFromGoLive"]), f"{tag} paybackFromGoLive")

        for k, gv in g["byCategory"].items():
            check(close(v["byCategory"][k], gv), f"{tag} byCategory.{k}")
        for k, gv in g["byClass"].items():
            check(close(v["byClass"][k], gv), f"{tag} byClass.{k}")
        for k, gv in g["byMaturity"].items():
            check(close(v["byMaturity"][k], gv), f"{tag} byMaturity.{k}")
        for k, gv in g["costs"].items():
            check(close(v["costs"][k], gv), f"{tag} costs.{k}")

        # monthly streams
        for m, gv in enumerate(g["monthlyNetHead"]):
            check(close(v["monthlyNet"][m], gv), f"{tag} monthlyNet[{m}]")
        for idx, gv in enumerate(g["monthlyBenefitsTail"]):
            check(close(v["monthlyBenefits"][56 + idx], gv), f"{tag} monthlyBenefits[{56 + idx}]")

        # scoring
        check(v["confidence"]["score"] == g["confidence"]["score"], f"{tag} confidence.score")
        check(v["confidence"]["band"] == g["confidence"]["band"], f"{tag} confidence.band")
        check(v["confidence"]["evidenceScore"] == g["confidence"]["evidenceScore"], f"{tag} confidence.evidence")
        check(v["confidence"]["guardrailPenalty"] == g["confidence"]["penalty"], f"{tag} confidence.penalty")
        check(v["strategicScore"] == g["strategicScore"], f"{tag} strategicScore")
        check(pr["score"] == g["priority"]["score"], f"{tag} priority.score")
        check(pr["band"] == g["priority"]["band"], f"{tag} priority.band")
        for comp, gcomp in zip(pr["components"], g["priority"]["components"]):
            check(comp["key"] == gcomp["key"], f"{tag} priority comp key")
            check(close(comp["raw"], gcomp["raw"]), f"{tag} priority raw {comp['key']}")
            check(close(comp["contribution"], gcomp["contribution"]), f"{tag} priority contrib {comp['key']}")

        # guardrails: same flags, same wording
        check(len(v["guardrails"]) == len(g["guardrails"]), f"{tag} guardrail count")
        for gr, ggr in zip(v["guardrails"], g["guardrails"]):
            check(gr["severity"] == ggr["severity"], f"{tag} guardrail severity")
            check(gr["title"] == ggr["title"], f"{tag} guardrail title {gr['title']!r}")
            check(gr["detail"] == ggr["detail"], f"{tag} guardrail detail {gr['title']!r}")

        # realisation history
        check(len(p["realisation"]) == len(g["realisation"]), f"{tag} realisation periods")
        for per, gper in zip(p["realisation"], g["realisation"]):
            for k, gv in gper.items():
                check(close(per[k], gv), f"{tag} realisation {per['period']}.{k}")

        # assumption register
        check(len(p["assumptions"]) == len(g["assumptions"]), f"{tag} assumption count")
        for a, ga in zip(p["assumptions"], g["assumptions"]):
            check(a["assumption"] == ga["assumption"], f"{tag} assumption text")
            check(close(a["value"], ga["value"]), f"{tag} assumption value")
            check(a["unit"] == ga["unit"], f"{tag} assumption unit")
            check(a["source"] == ga["source"], f"{tag} assumption source")
            check(a["owner"] == ga["owner"], f"{tag} assumption owner")
            check(a["evidence"] == ga["evidence"], f"{tag} assumption evidence")
            check(a["confidence"] == ga["confidence"], f"{tag} assumption confidence")

        # scenarios
        for s, gs in zip(run_scenarios(p, settings), g["scenarios"]):
            check(s["key"] == gs["key"], f"{tag} scenario key")
            check(close(s["valuation"]["threeYearValue"], gs["threeYear"]), f"{tag} scenario {s['key']} 3yr")
            check(close(s["valuation"]["roi"], gs["roi"]), f"{tag} scenario {s['key']} roi")
            check(close(s["valuation"]["npv"], gs["npv"]), f"{tag} scenario {s['key']} npv")
            check(close(s["valuation"]["paybackMonths"], gs["payback"]), f"{tag} scenario {s['key']} payback")

        # sensitivity
        tor = tornado(p, settings)
        check(len(tor) == len(g["tornado"]), f"{tag} tornado count")
        for t, gt in zip(tor, g["tornado"]):
            check(t["label"] == gt["label"], f"{tag} tornado label")
            check(t["benefitLabel"] == gt.get("benefitLabel"), f"{tag} tornado benefitLabel")
            check(close(t["low"], gt["low"]), f"{tag} tornado low {t['label']}")
            check(close(t["high"], gt["high"]), f"{tag} tornado high {t['label']}")
            check(t["rangeNote"] == gt["rangeNote"], f"{tag} tornado rangeNote {t['label']}")

        # recommendations
        recs = recommendations_for(p, settings, v)
        check(len(recs) == len(g["recommendations"]), f"{tag} rec count")
        for r, gr in zip(recs, g["recommendations"]):
            check(r["id"] == gr["id"], f"{tag} rec id")
            check(r["title"] == gr["title"], f"{tag} rec title")
            check(r["tone"] == gr["tone"], f"{tag} rec tone")
            check(r["body"] == gr["body"], f"{tag} rec body {r['id']}")
            check(r["impact"] == gr.get("impact"), f"{tag} rec impact {r['id']}")

    # portfolio-level insights
    ins = portfolio_insights(rows, settings)
    check(len(ins) == len(golden["insights"]), "insight count")
    for a, b in zip(ins, golden["insights"]):
        check(a["id"] == b["id"], f"insight id {a['id']}")
        check(a["tone"] == b["tone"], f"insight tone {a['id']}")
        check(a["metric"] == b.get("metric"), f"insight metric {a['id']}")
        check(a["text"] == b["text"], f"insight text {a['id']}")

    print(f"{checks:,} assertions across {len(rows)} products")
    if fails:
        print(f"\n{len(fails)} FAILURES (first 25):")
        for f in fails[:25]:
            print("  -", f)
        return 1
    print("PASS — Python engine reproduces the TypeScript engine exactly.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
